### ISSUE TITLE
mobxComponent decorator produces classes/functions which cannot be comsumed by other HOC functions

### ISSUE THREAD

**Issue by beckend** [xaviergonz/mobx-react-component#4]
```javascript
import { injectIntl } from 'react-intl'
```

TypeError: Cannot call a class as a function
    at classCallCheck (/home/linken/Coding/github/javascript-universal/node_modules/react-intl/lib/index.js:200:11)
    at new InjectIntl (/home/linken/Coding/github/javascript-universal/node_modules/react-intl/lib/index.js:553:7)

```javascript
@mobxComponent()
class MainLayoutBase extends MobxComponent<MyProps> {}
```

using function components 
```javascript
mobxObserver((props: MyProps) => {...})
```
was no problem

**Comment by beckend** [comment]
I debugged some, it turns out the decorator turn the class into a React element straight away, it already has been rendered at that stage

**Comment by beckend** [comment]
fails this check
```javascript
var classCallCheck = function (instance, Constructor) {
  if (!(instance instanceof Constructor)) {
    throw new TypeError("Cannot call a class as a function");
  }
};
```

also another HOC 
```javascript
import { withStyles } from '@material-ui/core'
```
fails the same when checking instance

**Comment by beckend** [comment]
I was able to sucessfully connect the component on the resulting MainLayoutBase.type, which React.memo exposes

**Comment by xaviergonz** [comment]
Hmm, I'll take a look anyway to see what's wrong

**Comment by xaviergonz** [comment]
That's weird, I just made this unit test and it worked (based on injectIntl implementation)
```
it("works inside a HOC", () => {
    function hoc<T extends React.ComponentClass<P>, P>(WrappedComponent: T): T {
        class HOC extends React.Component<P> {
            static WrappedComponent = WrappedComponent

            render() {
                return <WrappedComponent {...this.props as any} />
            }
        }

        return hoistNonReactStatics(HOC, WrappedComponent) as any
    }

    @mobxComponent()
    class TestComponent extends MobxComponent<{ x: number }> {
        render() {
            return <span>{this.props.x}</span>
        }
    }

    const Wrapped = hoc(TestComponent)

    const { container } = render(<Wrapped x={1} />)
    const span = container.querySelector("span")!
    expect(span.textContent).toBe("1")
})
```

**Comment by beckend** [comment]
Well uni tested or not, it does not really work for me in the real world, since i get that error above, actually have to connect it in this way to make it work.

```typescript
import { InjectedIntlProps, injectIntl } from 'react-intl'
import { MobxComponent, ReactContextValue, injectContext, mobxComponent } from 'mobx-react-component'

interface IPropsInjected extends InjectedIntlProps {
  readonly classes: {
    readonly appBarBottom: string
    readonly headerText: string
    readonly listNested: string
  }
}

@mobxComponent()
class MainLayoutBase extends MobxComponent<IPropsInjected> {...}

export const MainLayout = withStyles(theme => ({
  appBarBottom: {
    bottom: 0,
    top: 'auto',
  },
  headerText: {
    cursor: 'pointer',
  },
  listNested: {
    paddingLeft: theme.spacing.unit * 4,
  },
}))(injectIntl((MainLayoutBase as any).type as React.ComponentType<IPropsInjected>))

```

```json
{
  "mobx-react-component": "0.51.0",
  "react-intl": "^2.8.0"
}
```

I got the idea from https://github.com/styled-components/styled-components/issues/2146

**Comment by xaviergonz** [comment]
The problem seems to be an outdated version of hoist-non-react-statics, part of react-itl

https://github.com/yahoo/react-intl/blob/ee1dfb6f1b22fa274157656e1185d34f509c5f91/package.json#L67

I think if they update it to ^3.0.0 it should work ok, since it adds supports for React.forwardRef (which mobxComponent uses)

Alternatively, if you are using yarn, you can add this to your package.json
```
resolutions: {
  "hoist-non-react-statics": "3.3.0"
}
```
run `yarn install` again and try again
that will force that particular version to be used for all packages, rather than the old ones

**Comment by xaviergonz** [comment]
I just published a v0.52.0 that adds this

If for some reason you want to turn off ref emulation (for example some incompability or a slight speed bump) you
can do so using ```@mobxComponent({refEmulation: false})```

so you might try to use if with that particular component too to see if it works

**Comment by beckend** [comment]
opted for your last solution thank you

**Comment by beckend** [comment]
just a suggestion, why not have that flag false by default, i mean if they would need that ref, they would enable it.

**Comment by xaviergonz** [comment]
just to male it more like old components, which always have ref support by default, since the class version is more likely to help when converting old codebases

Either way I think you can just do this though
```ts
const mobxComponent2: typeof mobxComponent = (opts) => mobxComponent({refEmulation: false, ...opts});

@mobxComponent2
class ...
```
and that should be what you want
